[package]
name = "eos-primitives"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
eosio-core-derive = { path = "../eosio-core-derive" }
hex = "0.3"
keys = { package = "eos-keys", path = "../keys" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
eosio-core-macros = { path = "../eosio-core-macros" }

[features]
default = []
internal-use-only-root-path-is-eosio = ["eosio-core-derive/internal-use-only-root-path-is-eosio"]
